version: '3.8'
services:
  pgmaster:
    container_name: pgmaster
    image: postgres:14.12-alpine
    volumes:
      - ./volumes/pgmaster:/var/lib/postgresql/data/pgdata
      - ./src/main/resources/csv/people.csv:/etc/people.csv
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: otus
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=ru_RU'
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - pgnet
  pgslave1:
    container_name: pgslave1
    image: postgres:14.12-alpine
    volumes:
      - ./volumes/pgslave1:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: otus
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=ru_RU'
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    networks:
      - pgnet
  pgslave2:
    container_name: pgslave2
    image: postgres:14.12-alpine
    volumes:
      - ./volumes/pgslave2:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: otus
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=ru_RU'
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5434:5432"
    networks:
      - pgnet
  server:
    platform: linux/amd64
    environment:
      JAVA_TOOL_OPTIONS: '-agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n'
    build:
      context: .
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - pgmaster
      - pgslave1
      - pgslave2
    networks:
      - pgnet
networks:
  pgnet:
    driver: bridge