version: '3.8'
services:
  db:
    image: postgres:14.12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
      - ./src/main/resources/csv/people.csv:/etc/people.csv
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: otus
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=ru_RU'
      PGDATA: /var/lib/postgresql/data/pgdata
    expose:
      - 5432
  server:
    platform: linux/amd64
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data: